service: import-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  lambdaHashingVersion: 20201221

  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:PutObject"
      Resource:
        - "arn:aws:s3:::aws-angular-shop-bucket-s3/uploaded/*"
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource:
        - "arn:aws:s3:::aws-angular-shop-bucket-s3/*"
    - Effect: "Allow"
      Action:
        - "sqs:*"
      Resource:
        - "arn:aws:sqs:us-east-1:818211481183:catalog-items-queue"

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
    - http:
        method: get
        path: import
        cors: true
        request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: parser.importFileParser
    events:
      - s3:
          bucket: aws-angular-shop-bucket-s3
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true

resources:
    Resources:
        catalogItemsQueue:
            Type: "AWS::SQS::Queue"
            Properties:
                QueueName: catalog-items-queue